server:
  port: 8080
spring:
  application:
    name: pricingcalc
  datasource:
    url: jdbc:mysql://localhost:3306/ecom_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
